### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ToonTamilIndia** [sireeshdevaraj/SHIRO-MANHWA-API#2]
At first i thought https://manhwachan.vercel.app/ was https://manhwaclan.vercel.app/ but it was clan - chan (h/l)

Anyways it is not working

**Comment by sireeshdevaraj** [comment]
Hi @ToonTamilIndia, I abandoned the old version and have updated the new readme with the new API endpoint and domain. Please check it out.

Here's the new version:
GET MANHWAS : https://shiro.kuuhaku.space/manhwas
BASED on CATEGORIES : https://shiro.kuuhaku.space/manhwas?category=action

**Comment by ToonTamilIndia** [comment]
ok ❤️
